# Flask configuration
WTF_CSRF_ENABLED = True
SECRET_KEY = 'abcdefghijklmnopqrstuvwxyz'

# Twitter configuration
TWITTER_CONSUMER_KEY = 'SqdcRrxTBgHLM1YlG7rDBQK14'
TWITTER_CONSUMER_SECRET = 'i4s54izOO3gaOWMfePA0SimK0QrIfe2RLHuR85uCfRkq2rA3vh'
TWITTER_ACCESS_TOKEN_KEY = '756643756158386176-GNC9VUtuCdDaljiZk1Hu8Z1mECirCkX'
TWITTER_ACCESS_TOKEN_SECRET = '1XQwM5AD7juOvVbKcLCGHp60e1psO1GyBLvGA7XoAKUgf'
TWITTER_USER_NAME = 'broekhanger'
TWITTER_PASSWORD = 'IkHangLekker!'
